### ISSUE TITLE
Wrong tooltip position 

### ISSUE THREAD

**Issue by ritequila** [kkpoon/echarts-webcomponent#1]
Hi,

I'm trying to integrate echarts in polymer starter kit.
I have a problem with tooltip position: 
at the first mouseover event, tooltip position is what I expect (I tried various positioning attempts),
but after mouseout from chart and mouseover again in chart, tooltip take a wrong position.
I also tried directly on the [component page](https://www.webcomponents.org/element/kkpoon/echarts-webcomponent), with same result.

I added this parameters in component code:
"tooltip":{"trigger":"axis", "position": [10,10] }

has someone encountered the same problem?
Thank a lot!

**Comment by kkpoon** [comment]
I see the same problem too. investigating

**Comment by kkpoon** [comment]
Added a div element under the echarts-webcomponent element fixes the issue. Thanks for reporting the issue.

**Comment by ritequila** [comment]
Thanks!
Now, whit this solution, for intercept the echart instance and use setOption function, I used the following code (with **firstChild**):

`var  chart = echarts.getInstanceByDom(mychartId.firstChild);`
`chart.setOption(myOption);`
